/**
 * js/main.js — Chris LEE.PAPA Official Site
 */
'use strict';

const BASE_I18N = {
  ko:{nav_home:'Home',nav_works:'Works',nav_faith:'Faith',nav_squad:'Sister Squad',nav_play:'Play',nav_journal:'Journal',nav_about:'About',nav_music:'Music',nav_movie:'Movies',nav_book:'Books',nav_bible:'Bible',nav_worship:'Worship',nav_today:'Today',nav_squad_short:'SQUAD',nav_squad_1:'SISTER SQUAD',nav_squad_2:'SISTER SQUAD 2',nav_game:'GAME',share_title:'SHARE ARCHIVE',share_desc:'이곳의 기록과 영감을 소중한 사람들에게 전하세요.',share_copy:'COPY LINK',share_sns:'SNS SHARE',share_close:'Close',footer_text:'© 2026 Chris LEE.PAPA — The Creative Archive. All rights reserved.',footer_privacy:'개인정보처리방침',footer_terms:'이용약관',toast_copy:'링크가 복사되었습니다 ✓',toast_error:'지원하지 않는 브라우저입니다.'},
  en:{nav_home:'Home',nav_works:'Works',nav_faith:'Faith',nav_squad:'Sister Squad',nav_play:'Play',nav_journal:'Journal',nav_about:'About',nav_music:'Music',nav_movie:'Movies',nav_book:'Books',nav_bible:'Bible',nav_worship:'Worship',nav_today:'Today',nav_squad_short:'SQUAD',nav_squad_1:'SISTER SQUAD',nav_squad_2:'SISTER SQUAD 2',nav_game:'GAME',share_title:'SHARE ARCHIVE',share_desc:'Share the records and inspiration here with your loved ones.',share_copy:'COPY LINK',share_sns:'SNS SHARE',share_close:'Close',footer_text:'© 2026 Chris LEE.PAPA — The Creative Archive. All rights reserved.',footer_privacy:'Privacy Policy',footer_terms:'Terms of Use',toast_copy:'Link copied ✓',toast_error:'Sharing is not supported in this browser.'}
};
let i18n={ko:{...BASE_I18N.ko},en:{...BASE_I18N.en}};
let currentLang='ko';

function getSiteRoot(){const script=document.querySelector('script[src*="main.js"]');if(script&&script.src){try{return new URL('../',script.src).href}catch(_){}}return new URL('/',document.baseURI).href}
function getSiteFileUrl(file){return new URL(String(file).replace(/^\//,''),getSiteRoot()).href}
async function loadComponent(id,file){const target=document.getElementById(id);if(!target)return false;try{const response=await fetch(getSiteFileUrl(file),{cache:'no-cache'});if(!response.ok)throw new Error(`HTTP ${response.status}`);target.innerHTML=await response.text();return true}catch(error){console.warn(`[main.js] component load failed: ${file}`,error);return false}}
function getSavedLanguage(){try{const saved=localStorage.getItem('pref-lang');return saved==='en'||saved==='ko'?saved:'ko'}catch(_){return'ko'}}

async function loadComponents(){
  if(window.PAGE_I18N){i18n.ko={...BASE_I18N.ko,...(window.PAGE_I18N.ko||{})};i18n.en={...BASE_I18N.en,...(window.PAGE_I18N.en||{})};}
  await Promise.all([loadComponent('site-nav','components/header.html'),loadComponent('site-footer','components/footer.html')]);
  initScrollProgress();initNavScroll();initMobileMenu();initDesktopDropdowns();initActiveNavLink();initLangDropdown();initShareModal();initBibleLogout();initSecurity();initMouseOrb();
  setLanguage(getSavedLanguage());
  if(typeof window.onMainReady==='function')window.onMainReady();
  if((window.location.pathname||'').toLowerCase().includes('sistersquad2')){
    const ostScript=document.createElement('script');ostScript.src='/js/sistersquad2-ost.js?v=20260826';ostScript.defer=true;document.head.appendChild(ostScript);
  }
  if((window.location.pathname||'').toLowerCase().includes('sistersquad') && !(window.location.pathname||'').toLowerCase().includes('sistersquad2')){
    const contentScript=document.createElement('script');contentScript.src='/js/sistersquad1-content.js?v=20260826';contentScript.defer=true;document.head.appendChild(contentScript);
  }
  if((window.location.pathname||'').toLowerCase().includes('sistersquad-hub')){
    const squad1Card=document.querySelector('.sq-links .sq-link:nth-child(1)');
    if(squad1Card)squad1Card.style.backgroundImage="url('/images/sistersquad1.png')";
    const hubLangScript=document.createElement('script');
    hubLangScript.src='/js/sistersquad-hub-i18n.js?v=20260827';
    hubLangScript.defer=true;
    document.head.appendChild(hubLangScript);
  }
}
function initScrollProgress(){const bar=document.getElementById('scroll-progress');if(!bar)return;const update=()=>{const scroll=window.scrollY||window.pageYOffset||0;const max=document.documentElement.scrollHeight-window.innerHeight;bar.style.width=`${max>0?Math.max(0,Math.min(100,(scroll/max)*100)):0}%`};window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update,{passive:true});update()}
function initNavScroll(){const nav=document.getElementById('main-nav');if(!nav)return;const update=()=>nav.classList.toggle('scrolled',(window.scrollY||0)>40);window.addEventListener('scroll',update,{passive:true});update()}
function initMobileMenu(){const moreBtn=document.getElementById('mobileMoreBtn'),morePanel=document.getElementById('mobileMoreOverlay'),faithBtn=document.querySelector('[data-mobile-menu="faith"]'),faithPanel=document.getElementById('mobileFaithMenu'),projectsBtn=document.querySelector('[data-mobile-menu="squad"]'),projectsPanel=document.getElementById('mobileSquadMenu');const panels=[morePanel,faithPanel,projectsPanel].filter(Boolean),buttons=[moreBtn,faithBtn,projectsBtn].filter(Boolean);const closeAll=()=>{panels.forEach(p=>{p.classList.remove('active');p.setAttribute('aria-hidden','true')});buttons.forEach(b=>b.setAttribute('aria-expanded','false'));document.body.classList.remove('mobile-panel-open')};const openPanel=(p,b)=>{closeAll();p.classList.add('active');p.setAttribute('aria-hidden','false');if(b)b.setAttribute('aria-expanded','true');document.body.classList.add('mobile-panel-open')};[[moreBtn,morePanel],[faithBtn,faithPanel],[projectsBtn,projectsPanel]].forEach(([b,p])=>{if(!b||!p)return;b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();p.classList.contains('active')?closeAll():openPanel(p,b)})});document.querySelectorAll('#mobileMoreClose,#mobileSquadClose,.mobile-submenu-close').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();closeAll()}));panels.forEach(p=>{p.addEventListener('click',e=>{if(e.target===p)closeAll()});p.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeAll))});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAll()});window.addEventListener('resize',()=>{if(window.innerWidth>900)closeAll()})}
function closeDesktopDropdowns(except=null){document.querySelectorAll('.nav-dropdown-wrapper').forEach(w=>{if(w===except)return;w.classList.remove('active');const t=w.querySelector('.nav-dropdown-trigger');if(t){t.classList.remove('active');t.setAttribute('aria-expanded','false')}})}
function initDesktopDropdowns(){document.querySelectorAll('.nav-dropdown-wrapper').forEach(w=>{const t=w.querySelector('.nav-dropdown-trigger');if(!t)return;t.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const open=!w.classList.contains('active');closeDesktopDropdowns(w);w.classList.toggle('active',open);t.classList.toggle('active',open);t.setAttribute('aria-expanded',String(open))})});document.addEventListener('click',e=>{if(!e.target.closest('.nav-dropdown-wrapper')&&!e.target.closest('.lang-dropdown-wrapper'))closeDesktopDropdowns()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDesktopDropdowns()})}
function getCurrentPageKey(){let path=(window.location.pathname||'/').split('?')[0].split('#')[0].replace(/\/+$/,'');if(!path)return'index';return((path.split('/').pop()||'index').replace(/\.html$/i,'')||'index').toLowerCase()}
function markActivePage(page){document.querySelectorAll('[data-page]').forEach(link=>link.classList.toggle('active',(link.dataset.page||'').toLowerCase()===page))}
function activateDropdownContaining(selector){document.querySelectorAll('.nav-dropdown-wrapper').forEach(w=>{const t=w.querySelector('.nav-dropdown-trigger'),active=!!w.querySelector(selector);w.classList.toggle('active',active);if(t){t.classList.toggle('active',active);t.setAttribute('aria-expanded',String(active))}})}
function initActiveNavLink(){const page=getCurrentPageKey();markActivePage(page);if(['bible','worship'].includes(page))activateDropdownContaining(`[data-page="${page}"]`);if(['sistersquad','sistersquad2','sister-squad','game','gameinfo','miracleshot','miracleshot-ost'].includes(page))activateDropdownContaining(`[data-page="${page}"], [href*="sistersquad"], [href*="sister-squad"], [href*="gameinfo"], [href*="miracleshot"]`);if(page==='today')document.querySelectorAll('[data-page="today"]').forEach(l=>l.classList.add('active'));}
function initLangDropdown(){[['langWrapper','langToggleBtn'],['mobileLangWrapper','mobileLangToggleBtn']].forEach(([wrapperId,toggleId])=>{const wrapper=document.getElementById(wrapperId),toggle=document.getElementById(toggleId);if(!wrapper||!toggle)return;toggle.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const open=!wrapper.classList.contains('active');document.querySelectorAll('.lang-dropdown-wrapper').forEach(w=>w.classList.remove('active'));wrapper.classList.toggle('active',open);toggle.setAttribute('aria-expanded',String(open))});wrapper.querySelectorAll('.lang-btn').forEach(button=>button.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setLanguage(button.dataset.lang)}))});document.addEventListener('click',e=>{document.querySelectorAll('.lang-dropdown-wrapper').forEach(w=>{if(!w.contains(e.target)){w.classList.remove('active');const t=w.querySelector('.lang-current');if(t)t.setAttribute('aria-expanded','false')}})})}
function setLanguage(lang){currentLang=i18n[lang]?lang:'ko';document.documentElement.lang=currentLang;try{localStorage.setItem('pref-lang',currentLang)}catch(_){}document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(i18n[currentLang][key]!==undefined)el.innerHTML=i18n[currentLang][key]});const dict=i18n[currentLang];if(dict.meta_title)document.title=dict.meta_title;[['meta[name="description"]','meta_description'],['meta[property="og:title"]','og_title'],['meta[property="og:description"]','og_description'],['meta[name="twitter:title"]','twitter_title'],['meta[name="twitter:description"]','twitter_description']].forEach(([selector,key])=>{const el=document.querySelector(selector);if(el&&dict[key])el.setAttribute('content',dict[key])});document.querySelectorAll('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===currentLang));const text=currentLang==='ko'?'KOR':'ENG';const desktop=document.getElementById('currentLangText');if(desktop)desktop.textContent=text;const mobile=document.getElementById('mobileCurrentLangText');if(mobile)mobile.textContent=text;document.querySelectorAll('.lang-dropdown-wrapper').forEach(w=>w.classList.remove('active'));document.querySelectorAll('.lang-current').forEach(t=>t.setAttribute('aria-expanded','false'));if(typeof window.onLangChange==='function')window.onLangChange(currentLang)}
window.setLanguage=setLanguage;window.getCurrentLang=()=>currentLang;
function initShareModal(){const overlay=document.getElementById('shareOverlay');if(!overlay)return;const openButton=document.getElementById('shareOpenBtn'),closeButton=document.getElementById('shareCloseBtn'),copyButton=document.getElementById('shareCopyBtn'),snsButton=document.getElementById('shareSNSBtn');const close=()=>{overlay.classList.remove('active');overlay.setAttribute('aria-hidden','true');setTimeout(()=>{if(!overlay.classList.contains('active'))overlay.style.display='none'},300)},open=()=>{overlay.style.display='flex';overlay.setAttribute('aria-hidden','false');requestAnimationFrame(()=>overlay.classList.add('active'))};if(openButton)openButton.addEventListener('click',open);if(closeButton)closeButton.addEventListener('click',close);overlay.addEventListener('click',e=>{if(e.target===overlay)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&overlay.classList.contains('active'))close()});if(copyButton)copyButton.addEventListener('click',async()=>{const url=window.location.href;let ok=false;if(navigator.clipboard&&window.isSecureContext){try{await navigator.clipboard.writeText(url);ok=true}catch(_){} }if(!ok){const ta=document.createElement('textarea');ta.value=url;ta.style.cssText='position:fixed;left:-9999px;top:0;opacity:0';document.body.appendChild(ta);ta.focus();ta.select();try{ok=document.execCommand('copy')}catch(_){}ta.remove()}if(ok)showToast(i18n[currentLang].toast_copy);close()});if(snsButton)snsButton.addEventListener('click',async()=>{if(!navigator.share){showToast(i18n[currentLang].toast_error);return}try{await navigator.share({title:document.title||'Chris LEE.PAPA',text:'Chris LEE.PAPA',url:window.location.href})}catch(_){} })}
function showToast(message){const toast=document.getElementById('toast');if(!toast)return;toast.textContent=message;toast.style.display='block';clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.style.display='none',2500)}window.showToast=showToast;
function initBibleLogout(){document.querySelectorAll('#logoutBtn,#logoutButton,[data-action="logout"],[data-logout],.logout-btn,.logout-button').forEach(b=>{if(b.dataset.logoutBound==='true')return;b.dataset.logoutBound='true';b.addEventListener('click',e=>{e.preventDefault();try{Object.keys(localStorage).filter(k=>/bible|auth|user|login|session/i.test(k)).forEach(k=>localStorage.removeItem(k));Object.keys(sessionStorage).forEach(k=>sessionStorage.removeItem(k))}catch(_){}if(typeof window.onBibleLogout==='function')window.onBibleLogout();else window.location.href='/bible'})})}window.initBibleLogout=initBibleLogout;
function initSecurity(){document.addEventListener('contextmenu',e=>{if(e.target.closest('input,textarea,select,[contenteditable="true"]'))return;e.preventDefault()});document.addEventListener('copy',e=>{if(e.target.closest('input,textarea,select,[contenteditable="true"]'))return;if(window.getSelection&&window.getSelection().toString())e.preventDefault()});document.addEventListener('keydown',e=>{if(e.target.closest&&e.target.closest('input,textarea,select,[contenteditable="true"]'))return;const k=String(e.key||'').toUpperCase();if(k==='F12'||(e.ctrlKey&&e.shiftKey&&(k==='I'||k==='J'))||(e.ctrlKey&&k==='U')){e.preventDefault();return}if(e.ctrlKey&&['C','S','P'].includes(k)&&window.getSelection&&window.getSelection().toString())e.preventDefault()})}
function initMouseOrb(){const orb=document.getElementById('mouse-orb');if(!orb||!window.matchMedia||!window.matchMedia('(min-width:901px)').matches)return;document.addEventListener('mousemove',e=>{orb.style.left=`${e.clientX}px`;orb.style.top=`${e.clientY}px`},{passive:true})}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').then(()=>console.log('[main.js] ServiceWorker registered')).catch(e=>console.warn('[main.js] ServiceWorker failed',e)));
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',loadComponents);else loadComponents();
