'use strict';
(() => {
  const chars={g:{name:'길',img:'/images/g00.jpg',power:82,accuracy:94,curve:72},h:{name:'황',img:'/images/h00.jpg',power:96,accuracy:78,curve:55},k:{name:'고',img:'/images/k00.jpg',power:86,accuracy:82,curve:96},y:{name:'영',img:'/images/y00.jpg',power:88,accuracy:90,curve:78}};
  const state={mode:'cpu',p1:'h',p2:'g',set:1,total:[0,0],shots:[0,0],turn:0,aim:{power:0,curve:0,angle:0},targets:[],locked:false,charging:false,chargeStarted:0,chargeFrame:0,gesture:null,aimed:null,audio:null,lastHaptic:0};
  const $=id=>document.getElementById(id);
  const screens={setup:$('setupScreen'),game:$('gameScreen'),result:$('resultScreen')};
  const show=s=>{Object.values(screens).forEach(x=>x.classList.remove('active'));s.classList.add('active')};
  function requireLogin(){if(window.CLPAuth?.isLoggedIn?.()){$('accountBadge').textContent=String(window.CLPAuth.getUser?.()?.initials||'').toUpperCase();return true}if(window.CLPAuth?.showLoginModal)window.CLPAuth.showLoginModal({prefix:'clp-goal-login',onSuccess:()=>location.reload()});return false}
  function randomCharacter(){const keys=Object.keys(chars);return keys[Math.floor(Math.random()*keys.length)]}
  function haptic(ms=10){try{if(navigator.vibrate)navigator.vibrate(ms)}catch(_){}}
  function buildWall(){const wall=$('targetWall');wall.innerHTML='';state.targets=[];const values=[-100,-80,-60,-50,-40,-30,-20,-10,0,10,20,30,40,50,60,80,100];for(let i=0;i<63;i++){const value=values[Math.floor(Math.random()*values.length)],el=document.createElement('div');el.className='target '+(value>0?'plus':value<0?'minus':'zero');el.textContent=value>0?'+'+value:value;el.style.setProperty('--r',`${(Math.random()*6-3).toFixed(1)}deg`);el.style.setProperty('--z',`${Math.floor(Math.random()*35)}px`);el.dataset.value=String(value);wall.appendChild(el);state.targets.push(el)}}
  function updateHeader(){$('setNumber').textContent=state.set<=5?state.set:`OT${state.set-5}`;$('p1Total').textContent=state.total[0];$('p2Total').textContent=state.total[1];const c=chars[state.turn?state.p2:state.p1];$('turnLabel').textContent=`PLAYER ${state.turn+1} · ${c.name} TURN`}
  function updateOpponentUI(){const area=$('opponentSelectArea');area.classList.toggle('is-cpu',state.mode==='cpu');$('opponentName').textContent=state.mode==='cpu'?'COMPUTER · RANDOM':`PLAYER 2 · ${chars[state.p2].name}`;document.querySelectorAll('.opponent-card').forEach(card=>card.classList.toggle('selected',state.mode==='human'&&card.dataset.opponent===state.p2))}
  function selectSetup(){document.querySelectorAll('.mode-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.mode=b.dataset.mode;if(state.mode==='cpu')state.p2=randomCharacter();updateOpponentUI()});document.querySelectorAll('.character-card:not(.opponent-card)').forEach(card=>card.onclick=()=>{document.querySelectorAll('#characterGrid .character-card').forEach(x=>x.classList.remove('selected'));card.classList.add('selected');state.p1=card.dataset.character});document.querySelectorAll('.opponent-card').forEach(card=>card.onclick=()=>{if(state.mode!=='human')return;document.querySelectorAll('.opponent-card').forEach(x=>x.classList.remove('selected'));card.classList.add('selected');state.p2=card.dataset.opponent;$('opponentName').textContent=`PLAYER 2 · ${chars[state.p2].name}`});$('battleStart').onclick=()=>{if(state.mode==='cpu')state.p2=randomCharacter();if(requireLogin())startMatch()};$('againBtn').onclick=()=>{state.set=1;state.total=[0,0];state.shots=[0,0];state.turn=0;state.locked=false;show(screens.setup);if(state.mode==='cpu')state.p2=randomCharacter();updateOpponentUI()};updateOpponentUI()}
  function startMatch(){state.set=1;state.total=[0,0];state.shots=[0,0];state.turn=0;show(screens.game);applyProfiles();buildWall();resetBall();updateHeader()}
  function applyProfiles(){const a=chars[state.p1],b=chars[state.p2];$('p1Img').src=a.img;$('p1Label').textContent=`PLAYER 1 · ${a.name}`;$('p2Label').textContent=`PLAYER 2 · ${b.name}`;$('p2Img').src=b.img;$('accountBadge').textContent=String(window.CLPAuth?.getUser?.()?.initials||'').toUpperCase()}
  function resetBall(){const b=$('ball');b.textContent='⚽';b.style.left='50%';b.style.bottom='9%';b.style.transform='translateX(-50%) scale(1) rotate(0deg)';b.style.opacity='1';b.style.transition='';b.classList.remove('kicking','dragging');state.aim={power:0,curve:0,angle:0};state.locked=false;state.charging=false;state.gesture=null;state.aimed=null;state.lastHaptic=0;cancelAnimationFrame(state.chargeFrame);clearAim();updateAim();$('kickBtn').disabled=state.mode==='cpu'&&state.turn===1}
  function updateAim(){$('powerValue').textContent=state.aim.power+'%';$('curveValue').textContent=(state.aim.curve>0?'+':'')+state.aim.curve;$('angleValue').textContent=(state.aim.angle>0?'+':'')+state.aim.angle+'°';const fill=$('powerFill');if(fill)fill.style.width=state.aim.power+'%';const meter=document.querySelector('.power-meter');if(meter)meter.style.setProperty('--power',state.aim.power+'%')}
  function updateCharge(now){if(!state.charging)return;const elapsed=now-state.chargeStarted,cycle=3200,phase=elapsed%cycle,raw=phase<=1600?phase/1600:(3200-phase)/1600;state.aim.power=Math.round(raw*100);updateAim();if(state.aim.power>=88&&state.aim.power<=92&&now-state.lastHaptic>350){haptic(8);state.lastHaptic=now}state.chargeFrame=requestAnimationFrame(updateCharge)}
  function getPoint(e){return e.touches?e.touches[0]:e}
  function updateGesture(e){if(!state.gesture||state.locked)return;const p=getPoint(e),dx=p.clientX-state.gesture.x,dy=p.clientY-state.gesture.y;if(Math.hypot(dx,dy)<4)return;state.aim.angle=Math.round(Math.max(-45,Math.min(45,dx/125*45)));state.aim.curve=Math.round(Math.max(-100,Math.min(100,-dy/125*100)));updateAim();aimTarget()}
  function clearAim(){if(state.aimed)state.aimed.classList.remove('aimed');state.aimed=null}
  function aimTarget(){const t=nearestTarget(state.aim.power,state.aim.angle,state.aim.curve,true);if(t!==state.aimed){if(state.aimed)state.aimed.classList.remove('aimed');state.aimed=t;if(t)t.classList.add('aimed')}}
  function nearestTarget(power,angle,curve,includeHit=false){const available=state.targets.filter(t=>includeHit||!t.classList.contains('hit'));if(!available.length)return null;const wall=$('targetWall').getBoundingClientRect(),xNorm=.5+(angle/45)*.46,yNorm=.53-(curve/100)*.34+(power/100)*.08,wantedX=wall.left+wall.width*Math.max(.03,Math.min(.97,xNorm)),wantedY=wall.top+wall.height*Math.max(.05,Math.min(.95,yNorm));let best=null,bestDistance=Infinity;available.forEach(t=>{const r=t.getBoundingClientRect(),d=Math.hypot(r.left+r.width/2-wantedX,r.top+r.height/2-wantedY);if(d<bestDistance){bestDistance=d;best=t}});return best}
  function playTone(type){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;if(!state.audio)state.audio=new A();if(state.audio.state==='suspended')state.audio.resume();const o=state.audio.createOscillator(),g=state.audio.createGain();o.connect(g);g.connect(state.audio.destination);const now=state.audio.currentTime;o.type=type==='hit'?'triangle':'sine';o.frequency.setValueAtTime(type==='hit'?180:85,now);o.frequency.exponentialRampToValueAtTime(type==='hit'?75:42,now+.18);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(type==='hit'?.18:.1,now+.012);g.gain.exponentialRampToValueAtTime(.0001,now+.22);o.start(now);o.stop(now+.23)}catch(_){}}
  function impact(target,value){if(target){target.classList.add('hit-impact');setTimeout(()=>target.classList.remove('hit-impact'),260)}document.body.classList.add(value?'goal-score-impact':'goal-miss-impact');setTimeout(()=>document.body.classList.remove('goal-score-impact','goal-miss-impact'),260);haptic(value?22:8)}
  function animateKick(power,angle,curve,onDone){const b=$('ball'),stage=$('wallStage'),rect=stage.getBoundingClientRect(),target=nearestTarget(power,angle,curve),tr=target?.getBoundingClientRect();clearAim();playTone('kick');haptic(12);const sx=rect.width*.5,sy=rect.height*.91,tx=tr?tr.left+tr.width/2-rect.left:rect.width*(.5+angle*.01),ty=tr?tr.top+tr.height/2-rect.top:rect.height*.35,lift=Math.max(75,rect.height*(.14+power*.0024)),duration=Math.max(460,930-power*2.5),curveOffset=(curve/100)*rect.width*.20; b.classList.remove('dragging');b.classList.add('kicking');b.style.transition='none';const started=performance.now();const frame=now=>{const t=Math.min(1,(now-started)/duration),ease=1-Math.pow(1-t,3),u=1-ease,bend=Math.sin(Math.PI*t)*curveOffset,controlX=(sx+tx)/2+bend,controlY=Math.max(0,sy-lift),x=u*u*sx+2*u*ease*controlX+ease*ease*tx,y=u*u*sy+2*u*ease*controlY+ease*ease*ty,scale=1-.68*ease;b.style.left=x/rect.width*100+'%';b.style.bottom=(rect.height-y)/rect.height*100+'%';b.style.transform=`translateX(-50%) scale(${scale.toFixed(3)}) rotate(${(curve*4*t).toFixed(1)}deg) skewX(${(angle*.1*t).toFixed(1)}deg)`;if(t<1)requestAnimationFrame(frame);else{b.classList.remove('kicking');if(target)target.classList.add('hit');b.style.opacity='.08';onDone(target)}};requestAnimationFrame(frame)}
  function finishShot(value){state.total[state.turn]+=value;state.shots[state.turn]++;updateHeader();setTimeout(()=>{if(state.turn===0){state.turn=1;buildWall();resetBall();updateHeader();if(state.mode==='cpu')setTimeout(cpuKick,650)}else if(state.set<5){state.set++;state.turn=0;buildWall();resetBall();updateHeader()}else if(state.total[0]===state.total[1]){state.set++;state.turn=0;buildWall();resetBall();updateHeader()}else finishMatch()},900)}
  function humanKick(){if(state.locked)return;state.locked=true;state.charging=false;cancelAnimationFrame(state.chargeFrame);const {power,angle,curve}=state.aim,target=nearestTarget(power,angle,curve);if(!target){showShotPopup(0);finishShot(0);return}const r=target.getBoundingClientRect(),wall=$('targetWall').getBoundingClientRect(),xNorm=.5+(angle/45)*.46,yNorm=.53-(curve/100)*.34+(power/100)*.08,desiredX=wall.left+wall.width*xNorm,desiredY=wall.top+wall.height*yNorm,distance=Math.hypot(r.left+r.width/2-desiredX,r.top+r.height/2-desiredY),player=chars[state.p1],hitRadius=Math.max(30,34+(player.accuracy-75)*.38),hit=distance<=hitRadius,quality=power>=88&&power<=92?'PERFECT':power>=70?'GOOD':'WEAK';animateKick(power,angle,curve,landed=>{const value=hit&&landed===target?Number(landed.dataset.value):0;impact(landed,value);if(value)playTone('hit');showShotPopup(value,quality);finishShot(value)})}
  function cpuKick(){if(state.locked)return;state.locked=true;const c=chars[state.p2],power=68+Math.floor(Math.random()*28),angle=Math.floor(Math.random()*55)-27,curve=Math.floor(Math.random()*70)-35;state.aim={power,angle,curve};updateAim();setTimeout(()=>{const target=nearestTarget(power,angle,curve),wall=$('targetWall').getBoundingClientRect();let hit=false;if(target){const r=target.getBoundingClientRect(),xNorm=.5+(angle/45)*.46,yNorm=.53-(curve/100)*.34+(power/100)*.08,d=Math.hypot(r.left+r.width/2-(wall.left+wall.width*xNorm),r.top+r.height/2-(wall.top+wall.height*yNorm));hit=d<=Math.max(30,34+(c.accuracy-75)*.38)}animateKick(power,angle,curve,landed=>{const value=hit&&landed===target?Number(landed.dataset.value):0;impact(landed,value);if(value)playTone('hit');showShotPopup(value);finishShot(value)})},250)}
  function showShotPopup(value,quality){const p=document.createElement('div');p.className='shot-popup '+(value>0?'positive':value<0?'negative':'miss');p.textContent=value>0?'+'+value:value<0?String(value):'MISS';if(quality&&value)p.dataset.quality=quality;document.body.appendChild(p);setTimeout(()=>p.remove(),1100)}
  function finishMatch(){show(screens.result);$('finalP1').textContent=state.total[0];$('finalP2').textContent=state.total[1];$('resultTitle').textContent=state.total[0]>state.total[1]?'PLAYER 1 WINS':state.total[0]<state.total[1]?'PLAYER 2 WINS':'DRAW';$('resultMessage').textContent=state.total[0]>state.total[1]?'MIRACLE SHOT!':state.total[0]<state.total[1]?'GREAT SHOT!':'TIED MATCH!'}
  function bindDrag(){const b=$('ball');const start=e=>{if((state.turn===1&&state.mode==='cpu')||state.locked)return;const p=getPoint(e);state.gesture={x:p.clientX,y:p.clientY};state.charging=true;state.chargeStarted=performance.now();state.aim.power=0;state.aim.angle=0;state.aim.curve=0;b.classList.add('dragging');updateAim();aimTarget();state.chargeFrame=requestAnimationFrame(updateCharge);try{b.setPointerCapture(e.pointerId)}catch(_){}e.preventDefault()};const move=e=>{if(!state.gesture||state.locked)return;updateGesture(e);e.preventDefault()};const end=()=>{if(!state.gesture)return;state.gesture=null;state.charging=false;cancelAnimationFrame(state.chargeFrame);b.classList.remove('dragging');clearAim();if(state.aim.power>=12)humanKick();else{state.aim.power=0;updateAim()}};b.addEventListener('pointerdown',start,{passive:false});b.addEventListener('pointermove',move,{passive:false});b.addEventListener('pointerup',end);b.addEventListener('pointercancel',end);$('kickBtn').onclick=()=>{if(state.aim.power>=12)humanKick()}}
  selectSetup();bindDrag();if(window.CLPAuth?.isLoggedIn?.())$('accountBadge').textContent=String(window.CLPAuth.getUser?.()?.initials||'').toUpperCase();else if(window.CLPAuth?.showLoginModal)setTimeout(()=>window.CLPAuth.showLoginModal({prefix:'clp-goal-login',onSuccess:()=>location.reload()}),50);
})();