'use strict';
(()=>{
const chars={g:{name:'길',img:'/images/g00.jpg',power:82,accuracy:94,curve:72},h:{name:'황',img:'/images/h00.jpg',power:96,accuracy:78,curve:55},k:{name:'고',img:'/images/k00.jpg',power:86,accuracy:82,curve:96},y:{name:'영',img:'/images/y00.jpg',power:88,accuracy:90,curve:78}};
const state={mode:'cpu',p1:'h',p2:'g',round:1,total:[0,0],roundScore:[0,0],roundWins:[0,0],shots:[0,0],turn:0,aim:{power:0,curve:0,angle:0},targets:[],locked:false,charging:false,chargeStarted:0,chargeFrame:0,targetFrame:0,gesture:null,aimed:null,audio:null,lastHaptic:0,lastTargetMove:0,cpuTimer:0};
const $=id=>document.getElementById(id),screens={setup:$('setupScreen'),game:$('gameScreen'),result:$('resultScreen')};
const show=s=>{Object.values(screens).forEach(x=>x.classList.remove('active'));s.classList.add('active')};
function requireLogin(){if(window.CLPAuth?.isLoggedIn?.())return true;if(window.CLPAuth?.showLoginModal)window.CLPAuth.showLoginModal({prefix:'clp-goal-login',onSuccess:()=>location.reload()});return false}
function randomCharacter(){const keys=Object.keys(chars);return keys[Math.floor(Math.random()*keys.length)]}
function haptic(ms=10){try{if(navigator.vibrate)navigator.vibrate(ms)}catch(_){} }
function buildWall(){const wall=$('targetWall');wall.innerHTML='';state.targets=[];const values=[-100,-80,-60,-50,-40,-30,-20,-10,0,10,20,30,40,50,60,80,100];for(let i=0;i<63;i++){const value=values[Math.floor(Math.random()*values.length)],el=document.createElement('div');el.className='target '+(value>0?'plus':value<0?'minus':'zero');el.textContent=value>0?'+'+value:value;el.style.setProperty('--r',`${(Math.random()*6-3).toFixed(1)}deg`);el.style.setProperty('--z',`${Math.floor(Math.random()*35)}px`);el.dataset.value=String(value);wall.appendChild(el);state.targets.push(el)}}
function updateHeader(){$('setNumber').textContent=state.round;$('roundTitle').textContent=`ROUND ${state.round}`;$('p1Total').textContent=state.roundScore[0];$('p2Total').textContent=state.roundScore[1];$('p1Shots').textContent=`${state.shots[0]}/10 SHOTS`;$('p2Shots').textContent=`${state.shots[1]}/10 SHOTS`;updateTurnLabel()}
function updateTurnLabel(){const c=chars[state.turn?state.p2:state.p1];$('turnLabel').textContent=`PLAYER ${state.turn+1} · ${c.name} TURN`}
function updateOpponentUI(){const area=$('opponentSelectArea');area.classList.toggle('is-cpu',state.mode==='cpu');$('opponentName').textContent=state.mode==='cpu'?'COMPUTER · RANDOM':`PLAYER 2 · ${chars[state.p2].name}`;document.querySelectorAll('.opponent-card').forEach(card=>card.classList.toggle('selected',state.mode==='human'&&card.dataset.opponent===state.p2))}
function selectSetup(){document.querySelectorAll('.mode-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.mode=b.dataset.mode;if(state.mode==='cpu')state.p2=randomCharacter();updateOpponentUI()});document.querySelectorAll('.character-card:not(.opponent-card)').forEach(card=>card.onclick=()=>{document.querySelectorAll('#characterGrid .character-card').forEach(x=>x.classList.remove('selected'));card.classList.add('selected');state.p1=card.dataset.character});document.querySelectorAll('.opponent-card').forEach(card=>card.onclick=()=>{if(state.mode!=='human')return;document.querySelectorAll('.opponent-card').forEach(x=>x.classList.remove('selected'));card.classList.add('selected');state.p2=card.dataset.opponent;$('opponentName').textContent=`PLAYER 2 · ${chars[state.p2].name}`});$('battleStart').onclick=()=>{if(state.mode==='cpu')state.p2=randomCharacter();if(requireLogin())startMatch()};$('againBtn').onclick=()=>{clearTimeout(state.cpuTimer);state.cpuTimer=0;state.round=1;state.total=[0,0];state.roundScore=[0,0];state.roundWins=[0,0];state.shots=[0,0];state.turn=0;state.locked=false;show(screens.setup);if(state.mode==='cpu')state.p2=randomCharacter();updateOpponentUI()};updateOpponentUI()}
function startMatch(){clearTimeout(state.cpuTimer);state.cpuTimer=0;state.round=1;state.total=[0,0];state.roundScore=[0,0];state.roundWins=[0,0];state.shots=[0,0];state.turn=0;state.locked=false;show(screens.game);applyProfiles();startRound()}
function startRound(){clearTimeout(state.cpuTimer);state.cpuTimer=0;state.roundScore=[0,0];state.shots=[0,0];state.turn=0;state.locked=false;buildWall();resetBall();updateHeader()}
function applyProfiles(){const a=chars[state.p1],b=chars[state.p2];$('p1Img').src=a.img;$('p1Label').textContent=`PLAYER 1 · ${a.name}`;$('p2Label').textContent=`PLAYER 2 · ${b.name}`;$('p2Img').src=b.img}
function resetBall(){const b=$('ball');state.locked=false;b.textContent='⚽';b.style.left='50%';b.style.bottom='9%';b.style.transform='translateX(-50%) scale(1) rotate(0deg)';b.style.opacity='1';b.style.transition='';b.classList.remove('kicking','dragging');state.aim={power:0,curve:0,angle:0};state.charging=false;state.gesture=null;state.aimed=null;state.lastHaptic=0;state.lastTargetMove=0;cancelAnimationFrame(state.chargeFrame);cancelAnimationFrame(state.targetFrame);clearAim();updateAim();$('kickBtn').disabled=state.mode==='cpu'&&state.turn===1}
function updateAim(){$('powerValue').textContent=state.aim.power+'%';$('curveValue').textContent='—';$('angleValue').textContent='—';const fill=$('powerFill');if(fill)fill.style.width=state.aim.power+'%';const meter=document.querySelector('.power-meter');if(meter)meter.style.setProperty('--power',state.aim.power+'%')}
function updateCharge(now){if(!state.charging)return;const elapsed=now-state.chargeStarted,cycle=2600,phase=elapsed%cycle,raw=phase<=1300?phase/1300:(2600-phase)/1300;state.aim.power=Math.round(raw*100);updateAim();if(state.aim.power>=88&&state.aim.power<=92&&now-state.lastHaptic>350){haptic(8);state.lastHaptic=now}state.chargeFrame=requestAnimationFrame(updateCharge)}
function clearAim(){if(state.aimed)state.aimed.classList.remove('aimed');state.aimed=null}
function pickRandomTarget(){const available=state.targets.filter(t=>!t.classList.contains('hit'));return available.length?available[Math.floor(Math.random()*available.length)]:null}
function updateRandomTarget(now){if(!state.charging||state.locked)return;if(now-state.lastTargetMove>115){const next=pickRandomTarget();if(next&&next!==state.aimed){if(state.aimed)state.aimed.classList.remove('aimed');state.aimed=next;next.classList.add('aimed');state.aim.angle=Math.round(Math.random()*90-45);state.aim.curve=Math.round(Math.random()*200-100);state.lastTargetMove=now}}state.targetFrame=requestAnimationFrame(updateRandomTarget)}
function playTone(type){try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;if(!state.audio)state.audio=new A();if(state.audio.state==='suspended')state.audio.resume();const o=state.audio.createOscillator(),g=state.audio.createGain();o.connect(g);g.connect(state.audio.destination);const now=state.audio.currentTime;o.type=type==='hit'?'triangle':'sine';o.frequency.setValueAtTime(type==='hit'?180:85,now);o.frequency.exponentialRampToValueAtTime(type==='hit'?75:42,now+.18);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(type==='hit'?.18:.1,now+.012);g.gain.exponentialRampToValueAtTime(.0001,now+.22);o.start(now);o.stop(now+.23)}catch(_){} }
function impact(target,value){if(target){target.classList.add('hit-impact');setTimeout(()=>target.classList.remove('hit-impact'),260)}document.body.classList.add(value>0?'goal-score-impact':value<0?'goal-miss-impact':'goal-zero-impact');setTimeout(()=>document.body.classList.remove('goal-score-impact','goal-miss-impact','goal-zero-impact'),260);haptic(value?22:8)}
function animateKick(power,target,onDone){const b=$('ball'),stage=$('wallStage'),rect=stage.getBoundingClientRect(),tr=target?.getBoundingClientRect();clearAim();playTone('kick');haptic(12);const sx=rect.width*.5,sy=rect.height*.91,tx=tr?tr.left+tr.width/2-rect.left:rect.width*.5,ty=tr?tr.top+tr.height/2-rect.top:rect.height*.35,lift=Math.max(75,rect.height*(.14+power*.0024)),duration=Math.max(460,930-power*2.5);b.classList.remove('dragging');b.classList.add('kicking');b.style.transition='none';const started=performance.now();const frame=now=>{const t=Math.min(1,(now-started)/duration),ease=1-Math.pow(1-t,3),u=1-ease,controlX=(sx+tx)/2,controlY=Math.max(0,sy-lift),x=u*u*sx+2*u*ease*controlX+ease*ease*tx,y=u*u*sy+2*u*ease*controlY+ease*ease*ty,scale=1-.68*ease;b.style.left=x/rect.width*100+'%';b.style.bottom=(rect.height-y)/rect.height*100+'%';b.style.transform=`translateX(-50%) scale(${scale.toFixed(3)}) rotate(${(power*5*t).toFixed(1)}deg)`;if(t<1)requestAnimationFrame(frame);else{b.classList.remove('kicking');if(target)target.classList.add('hit');b.style.opacity='.08';onDone(target)}};requestAnimationFrame(frame)}
function queueCpuKick(delay=650){if(state.cpuTimer||state.mode!=='cpu'||state.turn!==1||state.shots[1]>=10)return;state.cpuTimer=setTimeout(()=>{state.cpuTimer=0;if(state.mode!=='cpu'||state.turn!==1||state.locked||state.shots[1]>=10)return;cpuKick()},delay)}
function finishShot(value){const player=state.turn;state.total[player]+=value;state.roundScore[player]+=value;state.shots[player]++;updateHeader();setTimeout(()=>{if(state.shots[0]>=10&&state.shots[1]>=10){finishRound();return}state.turn=player===0?1:0;resetBall();updateHeader();if(state.mode==='cpu'&&state.turn===1)queueCpuKick(700)},900)}
function finishRound(){const a=state.roundScore[0],b=state.roundScore[1];if(a>b)state.roundWins[0]++;else if(b>a)state.roundWins[1]++;const roundWinner=a>b?'PLAYER 1':b>a?'PLAYER 2':'NO WINNER';if(state.roundWins[0]>=2||state.roundWins[1]>=2||state.round>=3){setTimeout(finishMatch,200);return}state.round++;showRoundTransition(roundWinner,a,b);setTimeout(startRound,1300)}
function showRoundTransition(winner,a,b){const p=document.createElement('div');p.className='shot-popup '+(winner==='PLAYER 1'?'positive':winner==='PLAYER 2'?'negative':'miss');p.textContent=winner==='NO WINNER'?`ROUND ${state.round} TIE · ${a}:${b}`:`ROUND ${state.round} · ${winner} WINS`;document.body.appendChild(p);setTimeout(()=>p.remove(),1200)}
function humanKick(){if(state.locked||state.turn!==0)return;state.locked=true;state.charging=false;cancelAnimationFrame(state.chargeFrame);cancelAnimationFrame(state.targetFrame);const power=state.aim.power,target=state.aimed||pickRandomTarget();if(!target){state.locked=false;finishShot(0);return}const value=Number(target.dataset.value),quality=power>=88&&power<=92?'PERFECT':power>=70?'GOOD':'WEAK';animateKick(power,target,landed=>{impact(landed,value);if(value)playTone('hit');showShotPopup(value,quality);finishShot(value)})}
function cpuKick(){if(state.mode!=='cpu'||state.turn!==1||state.locked||state.shots[1]>=10)return;state.locked=true;const power=68+Math.floor(Math.random()*28);state.aim={power,angle:0,curve:0};updateAim();const target=pickRandomTarget();const value=target?Number(target.dataset.value):0;animateKick(power,target,landed=>{impact(landed,value);if(value)playTone('hit');showShotPopup(value);finishShot(value)})}
function showShotPopup(value,quality){const p=document.createElement('div');p.className='shot-popup '+(value>0?'positive':value<0?'negative':'miss');p.textContent=value>0?'+'+value:value<0?String(value):'0';if(quality)p.dataset.quality=quality;document.body.appendChild(p);setTimeout(()=>p.remove(),1100)}
function finishMatch(){clearTimeout(state.cpuTimer);state.cpuTimer=0;show(screens.result);$('finalP1').textContent=state.total[0];$('finalP2').textContent=state.total[1];$('resultTitle').textContent=state.roundWins[0]>state.roundWins[1]?'PLAYER 1 WINS':state.roundWins[0]<state.roundWins[1]?'PLAYER 2 WINS':'DRAW';$('roundWins').textContent=`ROUND WINS · PLAYER 1 ${state.roundWins[0]} — ${state.roundWins[1]} PLAYER 2`;$('resultMessage').textContent=state.roundWins[0]>state.roundWins[1]?'MIRACLE SHOT!':state.roundWins[0]<state.roundWins[1]?'GREAT SHOT!':'TIED MATCH!' }
function bindDrag(){const b=$('ball'),start=e=>{if((state.turn===1&&state.mode==='cpu')||state.locked)return;state.gesture=true;state.charging=true;state.chargeStarted=performance.now();state.lastTargetMove=0;state.aim.power=0;state.aim.angle=0;state.aim.curve=0;b.classList.add('dragging');updateAim();const first=pickRandomTarget();if(first){state.aimed=first;first.classList.add('aimed')}state.chargeFrame=requestAnimationFrame(updateCharge);state.targetFrame=requestAnimationFrame(updateRandomTarget);try{b.setPointerCapture(e.pointerId)}catch(_){}e.preventDefault()},move=e=>{if(!state.gesture||state.locked)return;e.preventDefault()},end=()=>{if(!state.gesture)return;state.gesture=null;state.charging=false;cancelAnimationFrame(state.chargeFrame);cancelAnimationFrame(state.targetFrame);b.classList.remove('dragging');if(state.aim.power>=1)humanKick();else{clearAim();state.aim.power=0;updateAim()}};b.addEventListener('pointerdown',start,{passive:false});b.addEventListener('pointermove',move,{passive:false});b.addEventListener('pointerup',end);b.addEventListener('pointercancel',end);$('kickBtn').onclick=()=>{if(state.charging)return;if(state.aim.power>=1)humanKick()}}
selectSetup();bindDrag();if(window.CLPAuth?.isLoggedIn?.()){}else if(window.CLPAuth?.showLoginModal)setTimeout(()=>window.CLPAuth.showLoginModal({prefix:'clp-goal-login',onSuccess:()=>location.reload()}),50);
})();
